<div id="pnl_editfaveform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Favourite Module</div>
		<a id="pnl_editfaveform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editfaveform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editfaveform-form">

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_userfavemod_id" class="easyui-textbox" mapping="userfavemod_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Title</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_title" class="easyui-textbox" mapping="title"  maxlength="100"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Module Fullname</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_modulefullname" class="easyui-textbox" mapping="modulefullname"  maxlength="100"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'fullname harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Variance</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_variancename" class="easyui-textbox" mapping="variancename"  maxlength="100"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ForeColor</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_forecolor" class="easyui-textbox" mapping="forecolor"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">BackColor</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_backcolor" class="easyui-textbox" mapping="backcolor"  maxlength="30"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Icon</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_icon" class="easyui-textbox" mapping="icon"  maxlength="100"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editfaveform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">User</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editfaveform-txt_user_id" class="easyui-textbox" mapping="user_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editfaveform-autoadd" type="checkbox"><label for="pnl_editfaveform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editfaveform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editfaveform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editfaveform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editfaveform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editfaveform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
