<?php require_once dirname(__FILE__).'/fguser-list.phtml' ?>
<?php require_once dirname(__FILE__).'/fguser-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/fguser-groupsgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/fguser-groupsform.phtml' ?>
<?php require_once dirname(__FILE__).'/fguser-favegrid.phtml' ?>
<?php require_once dirname(__FILE__).'/fguser-faveform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/fguser-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
