<div id="pnl_list">
	<div class="fgta-page-title">Daftar Long Task</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<?php
		$customheadbutton = __DIR__.'/fglongtask-list-customheadbutton.phtml'; 
		if (is_file($customheadbutton)) {
			include $customheadbutton;
		} else { ?>
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php } ?>

		<?php
		$customsearch = __DIR__.'/fglongtask-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/fglongtask-list-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>

			<thead>
				<tr>
					<th mapping="longtask_id">longtask_id</th>
					<th mapping="longtask_name">longtask_name</th>
					<th mapping="longtask_start">longtask_start</th>
					<th mapping="longtask_expired">longtask_expired</th>
					<th mapping="longtask_progress" style="text-align: right"  formatter="row_format_number">longtask_progress</th>
					<th mapping="longtask_taskdescr">longtask_taskdescr</th>
					<th mapping="longtask_logfile">longtask_logfile</th>
					<th mapping="longtask_lastprogressid">longtask_lastprogressid</th>
					<th mapping="longtask_isrunning" type="checkbox">longtask_isrunning</th>
					<th mapping="longtask_isrequestcancel" type="checkbox">longtask_isrequestcancel</th>
					<th mapping="longtask_iscanceled" type="checkbox">longtask_iscanceled</th>
					<th mapping="longtask_iscomplete" type="checkbox">longtask_iscomplete</th>
					<th mapping="longtask_iserror" type="checkbox">longtask_iserror</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Name</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Start</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Expired</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Progress</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Task Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Logfile</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Last Progress ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Running</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Request Cancel</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Canceled</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Complete</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000; text-align: center">Error</td>

				</tr>
			</thead>

			<?php } ?>

		</table>
	</div>


	<?php
	$customfootbutton = __DIR__.'/fglongtask-list-customfootbutton.phtml'; 
	if (is_file($customfootbutton)) {
		include $customfootbutton;
	} 
	?>	


</div>