<div id="wrapper" class="report-wrapper">

	<div id="obj_report_header" class="report-header fullwidth">
		ini report header<br>
		ini report header<br>
		ini report header<br>
		ini report header<br>
		ini report header<br>
		ini report header<br>
		ini report header<br>
		ini report header<br>
	</div>


	<table class="report-table fullwidth" style="display:none" cellpadding="0" cellspacing="0"> 
		<thead id="obj_reporttable_header" class="report-page-header">
			<th class="rowhead rptdata-col-no" data-fill-color='CCCCCC'>No</th>
			<th class="rowhead rptdata-col-coacode" data-fill-color='CCCCCC'>Descr</th>
		</thead>

		<tfoot id="obj_reporttable_footer" class="report-page-footer">
			<tr id="obj_reporttable_loadinginfo">
				<td>
					<div id="obj_reporttable_loadingmessage" class="footerstatusbox" style="position: absolute; padding-top: 10px; font-weight: bold">Wait, report are still loading ...</div>
				</td>
			</tr>
		</tfoot>

		<tbody id="obj_reporttable_body">
		</tbody>
	</table>


	<div id="obj_report_footer" class="report-footer report-footer-hidden fullwidth" style="display:none">
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
		footer<br>
	</div>


</div> 