<div id="pnl_list">
	<div class="fgta-page-title">Daftar Messaging</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<?php
		$customheadbutton = __DIR__.'/msg-list-customheadbutton.phtml'; 
		if (is_file($customheadbutton)) {
			include $customheadbutton;
		} else { ?>
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>
		<?php } ?>

		<?php
		$customsearch = __DIR__.'/msg-list-customsearch.phtml'; 
		if (is_file($customsearch)) {
			include $customsearch;
		} else { ?>
		<!-- Simple Query -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<?php } ?>
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<?php
			$customview = __DIR__.'/msg-list-customview.phtml'; 
			if (is_file($customview)) {
				include $customview;
			} else { ?>

			<thead>
				<tr>
					<th mapping="msg_id">msg_id</th>
					<th mapping="msg_module">msg_module</th>
					<th mapping="msg_batch">msg_batch</th>
					<th mapping="msg_descr">msg_descr</th>
					<th mapping="msgtype_name">msgtype_name</th>
					<th mapping="msg_hp">msg_hp</th>
					<th mapping="msg_email">msg_email</th>
					<th mapping="msg_nama">msg_nama</th>
					<th mapping="msg_processbatch">msg_processbatch</th>
					<th mapping="server_messageid">server_messageid</th>
					<th mapping="msg_cbtable">msg_cbtable</th>
					<th mapping="msg_cbfieldkey">msg_cbfieldkey</th>
					<th mapping="msg_cbfieldvalue">msg_cbfieldvalue</th>
					<th mapping="msg_cbfieldstatus">msg_cbfieldstatus</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Module</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Batch</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Type</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">To HP</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">To Email</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">To Nama</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Process Batch</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">MessageID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Callback Table</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Callback PK</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Callback PK Value</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Callback Status Field</td>

				</tr>
			</thead>

			<?php } ?>

		</table>
	</div>


	<?php
	$customfootbutton = __DIR__.'/msg-list-customfootbutton.phtml'; 
	if (is_file($customfootbutton)) {
		include $customfootbutton;
	} 
	?>	


</div>