<style>
	.login-wrapper {
		position: fixed;
		overflow-Y: scroll;
		/*border: 3px solid #ff2a2a; */
		display:flex;
		width: calc(100vw - (100vw - 100%));
		height: 100vh;
		align-items: center;
		justify-content: center;
		background-color: #c9ced8;
		
		-webkit-touch-callout: none; /* iOS Safari */
		-webkit-user-select: none; /* Safari */
		-khtml-user-select: none; /* Konqueror HTML */
		-moz-user-select: none; /* Old versions of Firefox */
		-ms-user-select: none; /* Internet Explorer/Edge */
		user-select: none; /* Non-prefixed version, currently
								supported by Chrome, Edge, Opera and Firefox */		
	}

	.login-box {
		margin: 20px; width: 250px; 
		border: 1px solid #194c7b; 
		padding-bottom: 25px; 
		background-color: white;
		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
	}


	@media screen and (max-width: 520px) {
		.login-wrapper {
			border: 0px;
			align-items: flex-start;
			justify-content: flex-start;
			padding: 0px;	
			background-color: #ffffff			
		}

		.login-box {
			margin: 0px;
			width: 100%;
			border: 0px;
			padding: 0px;
			box-shadow: none;
		}
	}


	.email-login {
		position:relative;
		float: left;
		width: 100%;
		height:auto;
		margin-top: 20px;
		text-align:center;
}



	.u-form-group{
		width:100%;
		margin-bottom: 10px;


	}


	.u-form-group input[type="checkbox"] {
		border: 0px;
	}

	.u-form-group input[type="text"],
	.u-form-group input[type="password"]{
		width: 100%;
		height:45px;
		outline: none;
		border: 1px solid #ddd;
		padding: 0 10px;
		border-radius: 2px;
		color: #333;
		font-size:0.8rem;
		-webkit-transition:all 0.1s linear;
		-moz-transition:all 0.1s linear;
		transition:all 0.1s linear;
	}

	.u-form-group input:focus{
		border-color: #358efb;
	}

	.u-form-group button{
		width:100%;
		border: none;
		outline: none;
		color: #fff;
		font-size: 14px;
		font-weight: normal;
		padding: 14px 0;
		border-radius: 2px;
		text-transform: uppercase;
	}	


</style>


<div class="login-wrapper">


	<div class="login-box" >

		<div style="font-weight: bold; font-size: larger; margin-bottom: 18px; height: 100px; background-color: #194c7b; text-align: left; padding-top: 15px; padding-left: 10px">
			<img src="images/fgta.png" width="210px" height="53px" border="0px">
		</div>

		<div style="padding: 15px 15px 15px 15px; ">
			<div class="u-form-group">
				<input id="txt_username" type="text" placeholder="Username"/>
			</div>

			<div class="u-form-group">
				<input id="txt_password" type="password" placeholder="Password"/>
			</div>

			<div class="u-form-group">	
				<input type="checkbox" id="chk_rememberme" style="cursor:pointer">
				<label for="chk_rememberme" style="cursor:pointer">Remember me</label>
			</div>

			<div class="u-form-group" style="margin-top: 35px">
				<button id="btn_login" class="c8" style="cursor:pointer">Login</button>
			</div>


		</div>




		<!-- <div style="margin-left: 10px;" >
			<div style="width:225px; margin-top: 20px; margin-bottom: 5px">Username</div>
			<div style="width:225px">
				<input id="obj_txt_username" class="easyui-textbox" style="width:100%">
			</div>
		</div>

		<div style="margin-left: 10px;" >
			<div style="width:225px; margin-top: 20px; margin-bottom: 5px">Password</div>
			<div style="width:225px">
				<input id="obj_txt_password" class="easyui-passwordbox" style="width:100%">
			</div>
		</div>


		<div style="margin-top: 20px; margin-left: 10px;">
			<a id="btn_login" class="easyui-linkbutton c8">Login</a>
		</div>


		<div style="margin-top: 25px; margin-left: 10px;">
			<input id="obj_chk_rememberme" class="easyui-checkbox" label="Remember Me" labelPosition="after" labelAlign="left" labelWidth="100px" data-options="">
		</div> -->


	</div> 


</div>