<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Proses 02</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_id" class="easyui-textbox" mapping="pros_id" uppercase="true" maxlength="16" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_name" class="easyui-textbox" mapping="pros_name" uppercase="true" maxlength="60" style="width: 400px" data-options="multiline: false , required: true, invalidMessage: 'Nama harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_pros_iscommit" class="easyui-checkbox c1" mapping="pros_iscommit" data-options="label: 'Commit', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_commitby" class="easyui-textbox" mapping="pros_commitby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">CommitDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_commitdate" class="easyui-textbox" mapping="pros_commitdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Version</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_version" class="easyui-numberbox" mapping="pros_version" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_pros_isapprovalprogress" class="easyui-checkbox c1" mapping="pros_isapprovalprogress" data-options="label: 'Progress', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_pros_isapproved" class="easyui-checkbox c1" mapping="pros_isapproved" data-options="label: 'Approved', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_approveby" class="easyui-textbox" mapping="pros_approveby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_approvedate" class="easyui-textbox" mapping="pros_approvedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_pros_isdeclined" class="easyui-checkbox c1" mapping="pros_isdeclined" data-options="label: 'Declined', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_declineby" class="easyui-textbox" mapping="pros_declineby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_pros_declinedate" class="easyui-textbox" mapping="pros_declinedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_doc_id" class="easyui-combo" style="width: 400px" mapping="doc_id" display="doc_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'ID harus diisi', disabled: true"   validType="requiredcombo['pnl_edit-cbo_doc_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Dept</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_dept_id" class="easyui-combo" style="width: 400px" mapping="dept_id" display="dept_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Departmen Harus diisi', prompt: '-- PILIH --'"   validType="requiredcombo['pnl_edit-cbo_dept_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px" onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editapprovalgrid')">
					<div id="pnl_edit-txt_approval_title" class="detilgrid-text">Approval</div>
					<div id="pnl_edit-txt_approval_value" class="detilgrid-value">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px;" data-options="iconCls:'icon-print'">print</a>
		
			<a id="pnl_edit-btn_commit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px;" data-options="iconCls:'fgta-icon-commit'">Commit</a>			
			<a id="pnl_edit-btn_uncommit" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px;" data-options="iconCls:'fgta-icon-uncommit'">UnCommit</a>
			
		
				<a id="pnl_edit-btn_approve" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-posting'">Approve</a>
				<a id="pnl_edit-btn_decline" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-unposting'">Decline</a>
				
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>

