<?php require_once dirname(__FILE__).'/fgrole-list.phtml' ?>
<?php require_once dirname(__FILE__).'/fgrole-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/fgrole-permissiongrid.phtml' ?>
<?php require_once dirname(__FILE__).'/fgrole-permissionform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/fgrole-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
