


<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Role</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row">
			<div class="form_label_col">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_id" class="easyui-textbox" mapping="id" style="width: 100px">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Nama</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_nama" class="easyui-textbox" mapping="nama" style="width: 200px">
			</div>
		</div>	
		
		<div class="form_row">
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_isdisabled" class="easyui-checkbox c1" mapping="disabled" data-options="label: 'Disabled', labelPosition: 'after', disabled:false, checked: false">
			</div>
		</div>		

		<div class="form_row">
			<div class="form_label_col">Alamat</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_alamat" class="easyui-textbox" mapping="alamat" style="width: 400px" data-options="required:true,invalidMessage:'alamat wajib diisi'">
			</div>
		</div>	

		<div class="form_row">
			<div class="form_label_col">Tanggal</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_tanggal" class="easyui-datebox" style="width: 400px" mapping="tanggal" data-options="editable:false">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Gender</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_gender" class="easyui-combobox" style="width: 400px" mapping="gender" display="gendername" data-options="editable:false, valueField:'id', textField:'text'">
			</div>
		</div>

		<div class="form_row">
			<div class="form_label_col">Nilai</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_nilai" class="easyui-numberbox" mapping="nilai" style="width: 400px" data-options="">
			</div>
		</div>	



	</form>


	<!-- <div>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br>-<br></div> -->


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1" style="width">Simpan</a>
		</div>
	</div>	

	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol yang lin disini -->
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5" style="width">Hapus</a>
		</div>
	</div>

</div>