<div style="margin-left: 30px">

	<h2>Contoh eksekusi longrun process menggunakan microservice nodejs</h2>

	<div style="display:flex; margin-bottom: 20px">
		<a href="javascript:void(0)" id="btn_execute" class="easyui-linkbutton c8" style="width: 100px">Execute</a>
		<div id="pbr_progress" class="easyui-progressbar" style="width:200px; height: 28px; margin-left: 10px"></div>
	</div>
	<textarea id='txt_progressdisplay'  style="width: 600px; height: 300px; " readonly>
	</textarea>

</div>

