<div style="padding: 5px 5px 5px 30px;">

	<h3>Mengakses API</h3>

	<div>
		<input id="obj_txt_string" class="easyui-textbox" type="textbox" style="width: 400px" data-options="prompt:'Ketik sesuatu disini'">
	</div>

	<div style="margin-top: 10px">
		<a id="btn_execute_1" class="easyui-linkbutton c8">Eksekusi API (Error 404)</a>
	</div>

	<div style="margin-top: 10px">
		<a id="btn_execute_2" class="easyui-linkbutton c8">Eksekusi API</a>
	</div>



	<div style="margin-top: 10px">
		<a id="btn_execute_3" class="easyui-linkbutton c8">Eksekusi API (Limited)</a>
	</div>
</div>