<div style="padding: 5px 5px 5px 30px;">

	<h3>Mobile First Form Layout Dasar</h3>


	<div class="mfcontainer">


		<div class="mfrow">
			<div class="mffield">
				<div class="mflabel">Label</div>
				<div class="mfcomp"><input class="easyui-textbox" style="width:100%"></div>
			</div>

			<div class="mffield">
				<div class="mflabel">Label</div>
				<div class="mfcomp"><input class="easyui-textbox" style="width:100%"></div>
			</div>

			<div class="mffield">
				<div class="mflabel">Label</div>
				<div class="mfcomp"><input class="easyui-textbox" style="width:100%"></div>
			</div>			
			
		</div>


		<div class="mfrow">
			<div class="mffield">
				<div class="mflabel">Label</div>
				<div class="mfcomp"><input class="easyui-textbox" style="width:100%"></div>
			</div>

			<div class="mffield">
				<div class="mflabel">Label</div>
				<div class="mfcomp"><input class="easyui-textbox" style="width:100%"></div>
			</div>

			<div class="mffield">
				<div class="mflabel">Label</div>
				<div class="mfcomp"><input class="easyui-textbox" style="width:100%"></div>
			</div>			
			
		</div>

	</div>

</div>