<div style="margin: 10px">
	<div style="font-size: 1.2em; font-weight: bold">Welcome,</div> 
	<div style="font-size: 1.5em; font-weight: bold"><?=$this->userfullname?></div>

	<div id="pnl_fave" style="display: flex; flex-wrap: wrap; margin-top: 20px; margin-bottom: 20px">
		<div>Loading Favourite modules ...</div>
	</div>

	<div style="margin-top: 20px">
		<div style="display: inline-block; border-bottom: 1px solid #ccc; font-weight: bold; font-size: 1.3em">
			Recent Opened Apps
		</div>
	</div>
	<div>
		<!-- <a id="btn_test" href="javascript:void(0)" class="easyui-linkbutton">test</a> -->
	</div>
	<div style="height: 80px; margin-top: 5px">
		<table id="tbl_home-openap" >
			<!-- <tr>
				<td class="home-openap-fave-td">
					<img src="index.php/public/images/icon-fave-on.svg" style="width:12px; height:12px">
				</td>
				<td class="home-openap-title-td">Apps Name</td>
				<td class="home-openap-close-td">
					<img src="index.php/public/images/icon-openedapp-close.svg" style="width:12px; height:12px">
				</td>
			</tr> -->
		</table>
	</div>


</div>	