<?php require_once dirname(__FILE__).'/formgenjurn-list.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-jurnaldetilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-jurnaldetilform.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-jurnalpaymngrid.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-jurnalpaymnform.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-info.phtml' ?>
<?php require_once dirname(__FILE__).'/formgenjurn-log.phtml' ?>

