<?php require_once dirname(__FILE__).'/formdevjurn-list.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-jurnaldetilgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-jurnaldetilform.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-jurnalpaymngrid.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-jurnalpaymnform.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-info.phtml' ?>
<?php require_once dirname(__FILE__).'/formdevjurn-log.phtml' ?>

