<?php namespace FGTA4\module; 
if (!defined('FGTA4')) {
	die('Forbiden');
}
?><!DOCTYPE HTML>
<html>
	<head>
		
		<title><?=$this->title?></title>
		<!-- <base href="<?=__BASEADDRESS?>"> -->
		<base href="<?php echo $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']); ?> ">
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="manifest" href="manifest.json">
		<!-- <link rel="icon" sizes="192x192" href="images/<?=__ICON32?>">
		<link rel="apple-touch-icon" sizes="192x192" href="images/<?=__ICON32?>">
		 -->
		 <meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="application-name" content="<?=__APPDISPLAYNAME?>">
		<meta name="apple-mobile-web-app-title" content="<?=__APPDISPLAYNAME?>">
		<meta name="theme-color" content="#9c6ea7">
		<meta name="msapplication-navbutton-color" content="#9c6ea7">
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
		<meta name="msapplication-starturl" content="/">

		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
		<meta http-equiv="Pragma" content="no-cache" />
		<meta http-equiv="Expires" content="-1" />
		<meta name="modulefullname" content="<?=$this->reqinfo->modulefullname?>" />
		<meta name="variancename" content="<?=$this->reqinfo->variancename?>" />
		<meta name="basetitle" content="<?=$this->configuration->basetitle?>" />
		<meta name="home" content="<?=__STARTMODULE?>" />

		<style>
			@font-face {
				font-family: 'Droid Sans';
				font-style: normal;
				font-weight: 300;
				src: local('Droid Sans Regular'), local('DroidSans-Regular'), url('./templates/fgta-content/asset/droidsans.woff2') format('woff2');
				unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;	
				font-stretch: condensed;
			}


			html { 
				width: 100%;
				height: 100%;
				padding: 0;
				margin: 0;
				font-family: Droid Sans; 
				font-size: 14px;
			}

			body {
				width: 100%;
				height: 100%;
				padding: 0 0 0 0 ;
				margin: 0 0 0 0;							
				background-color: #ddd;	
				display: flex;
				flex-direction: column;
				min-height: 100vh;
				font-family: Droid Sans; 
				font-size: 14px;				
			}




			#page_head-big {
				width: 100%;
				background-color: aqua;
				z-index: 99995;
				position: fixed;
				opacity: 0;
			}


			#page_head-mini {
				width: 100%;
				background-color:blue;
				z-index: 99996;
				position: fixed;
				opacity: 0;
			}

			#page_head-logo {
				background-color:red;
				z-index: 99997;	
				position: fixed;
				opacity: 0;	
			}

			#page_head-menu {
				display: flex;
				flex-direction: row-reverse;
				align-items: flex-end;
				justify-content: flex-start; 
				z-index: 99999;
				font-size: 1em;
				position: fixed;
				right: 0px;
				margin-top: 10px;
				margin-bottom: 10px;
				margin-right: 10px;
			}


			#page_content {
				flex-grow: 1;
				align-self: stretch;
				vertical-align: top;
				position: relative;		
				opacity: 0;	
				z-index: 1000000;	
			}

			#page_footer {
				background-color: rgb(20, 20, 20);
				height: 300px;
				min-height: 300px;
				color:rgb(221, 221, 221)
			}


			.contentpanel {
				width: 100%;
				display: none
			}

			.headshadow {
				-webkit-box-shadow: 0px -8px 11px 8px rgba(0,0,0,0.75);
				-moz-box-shadow: 0px -8px 11px 8px rgba(0,0,0,0.75);
				box-shadow: 0px -8px 11px 8px rgba(0,0,0,0.75);
			}


			.pagetitle {
				font-weight: bold;
				font-size: 1.3em;
				margin-bottom: 20px;
			}


			.form_cell {
				display: flex;
				align-items: flex-start;
				margin-bottom: 10px;
			}

			.form_label_col {
				width: 90px;
				text-align: right;
				margin-right: 10px;
			}


		</style>

		

		
		
		<script>
			var useminiheader = '<?=property_exists($this, "useminiheader") ? ($this->useminiheader ? "true" : "false") : "false"  ?>';
			window.$fgta = {
				useminiheader: useminiheader === 'true' ? true : false,
				showmenulist: true,
				showaccount: true
			}			
		</script>
		<script src="index.php/jslibs/cookie.js"></script>
		<script src="index.php/jslibs/fgtacontenthead.js"></script>
		<?php
		$app_script_path = __LOCALCLIENT_DIR . "/script-content.js";
		if (\is_file($app_script_path)) {
		?>
		<script src="index.php/public/script-content.js"></script>
		<?php } ?>		
	</head>
	<body>

	

		<header id="page_head-mini" class="headshadow"></header>
		<header id="page_head-logo" ></header>
		<header id="page_head-big" class="headshadow"></header>
		<div id="page_head-menu">
			<div id="page_head-menu_account" style="opacity: 0;">
				<?php
				$this->auth->handlers = (object) array(
					'signin' => 'content/auth/signin',
					'signout' => 'content/auth/signout',
					'register' => 'content/auth/register',
					'account' => 'content/auth/account'
				);
				?>
				<?php
				$tp_account_path = __LOCALCLIENT_DIR . "/page-account.phtml";
				if (\is_file($tp_account_path)) {
					require_once $tp_account_path;
				} else { ?>
				control account disini
				<?php } ?>	
			</div>

			<div id="page_head-menu_split" style="opacity: 0;">
				&nbsp;|&nbsp;
			</div>

			<div id="page_head-menu_list" style="opacity: 0;">
				<?php
				$tp_menu_path = __LOCALCLIENT_DIR . "/page-menu.phtml";
				if (\is_file($tp_menu_path)) {
					require_once $tp_menu_path;
				} else { ?>
				menu halaman di sini
				<?php } ?>				
			</div>


		</div>


		<main id="page_content">
			<div style="margin: 20px 20px 50px 20px">
			<?php require_once $this->reqinfo->moduleviewpath ?>
			</div>
		</main>	

		<?php
		$tp_footer_path = __LOCALCLIENT_DIR . "/page-footer.phtml";
		if (\is_file($tp_footer_path)) {
			require_once $tp_footer_path;
		} else { ?>
		<footer id="page_footer">
			footer d
		</footer>
		<?php } ?>
	</body>
</html>
<?php require_once dirname(__FILE__).'/appactivator.phtml'; ?>


<!--
* lagi WFH di Kota Tangerang	
* 2020-07-07	
* panjitengkorak@null.net
-------------------------
END OF TEMPLATE -->