<div id="obj_framecontainer" class="page-frame-container">
</div>

<div id="obj_pageheader" class="hidden-element">
	<div class="page-descr">xxxx</div>
	<div class="page-paging">page x of y</div>
</div>


<div id="wrapper" class="report-wrapper">

	<div id="obj_report_header" class="report-header fullwidth">
		<div style="display: flex; justify-content: space-between">
			<div class="report-title">Page Title</div>
			<div id="obj_paging_page_1" class="page-paging">page x of y</div>
		</div>
		asfsf d<br>
		asfsf d<br>
		asfsf d<br>
		asfsf d<br>
		asfsf d<br>
		 
	</div>


	<table id="obj_reporttable" class="report-table fullwidth" cellpadding="0" cellspacing="0"> 
		<thead id="obj_reporttable_header" class="report-page-header">
			<th class="cell-header col-no" data-fill-color='CCCCCC'>No</th>
			<th class="cell-header col-descr" data-fill-color='CCCCCC'>Descr</th>
		</thead>

		<tfoot id="obj_reporttable_footer" class="report-page-footer">
			<tr id="obj_reporttable_loadinginfo">
				<td>
					<div id="obj_reporttable_loadingmessage" class="footerstatusbox" style="position: absolute; padding-top: 10px; font-weight: bold">Wait, report are still loading ...</div>
				</td>
			</tr>
		</tfoot>

		<tbody id="obj_reporttable_body">
		</tbody>


	</table>


	<div id="obj_report_footer" class="fullwidth report-footer report-footer-initial">
		<div class="report-footer-content">
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
			footer<br>
		</div>
	</div>


</div>